services:
  magic-ninja:
    build:
      context: .
      args: 
        - VITE_API_BASE=http://localhost
        - VITE_API_PORT=8080
        - VITE_IMAGE_URL=https://magic-ninja.s3.us-east-1.amazonaws.com
    ports:
      - "8080:3001"

    env_file:
      - .env
