name: magic-ninja
service:
  port: 80
  targetPort: 3001
  type: NodePort
  host: mage.ulicon.com
  tag: 1b68d103ce9350e49f2f39e5ff53d12ca7f9e3ae
  image: ghcr.io/sorjak/magic-ninja
env:
  SERVER_PORT: '3001'
  S3_BUCKET_NAME: magic-ninja
  DIRECTORY_BUCKET_NAME: magic-ninja--use1-az6--x-s3
