name: magic-ninja

service:
  port: 80
  targetPort: 3001
  type: NodePort
  host: mage.ulicon.com

env:
  SERVER_PORT: "3001"
  S3_BUCKET_NAME: "magic-ninja"
  DIRECTORY_BUCKET_NAME: "magic-ninja--use1-az6--x-s3"
