name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main # Triggers the workflow on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      # Grant write permissions for the GITHUB_TOKEN to commit and create a PR
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: source-repo

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./source-repo
          push: true
          tags: ghcr.io/sorjak/${{ github.event.repository.name }}:${{ github.sha }}
          build-args: |
            VITE_API_BASE=${{ vars.CLIENT_API_BASE }}
            VITE_API_PORT=${{ vars.CLIENT_API_PORT }}
            VITE_IMAGE_URL=${{ vars.CLIENT_IMAGE_URL }}

      - name: Update values.yaml in source repo
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'source-repo/k8s/values.yaml'
          propertyPath: 'service.tag'
          value: ${{ github.sha }}
          commitChange: false

      - name: Checkout the destination repo (Ninetales ArgoCD)
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/ninetales-argocd
          token: ${{ secrets.ACTIONS_PAT }}
          path: ninetales-argocd

      - name: Copy Changes from source to destination repo
        run: |
          mkdir -p ninetales-argocd/${GITHUB_REPOSITORY#*/}
          rm -rf ninetales-argocd/${GITHUB_REPOSITORY#*/}/*
          cp -r source-repo/k8s/* ninetales-argocd/${GITHUB_REPOSITORY#*/}

      - name: Commit and Push using Git commands
        run: |
          cd ninetales-argocd
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated update $GITHUB_SHA from $GITHUB_REPOSITORY"
          git push
